# Test Best Models

Test notebook to generate the statistics of the different models found with AMS. First load the required libraries

In [1]:
import datetime
import logging
import sys
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler

from keras.callbacks import LearningRateScheduler
from keras.optimizers import Adam
import keras.backend as K
from keras.models import model_from_json

from sklearn.model_selection import KFold
from scipy import stats

#sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
sys.path.append('/media/controlslab/DATA/Projects')

import ann_framework.aux_functions as aux_functions

import automatic_model_selection
from automatic_model_selection import Configuration
from ann_encoding_rules import Layers
import fetch_to_keras
#from CMAPSAuxFunctions import TrainValTensorBoard

#Tunable model
from ann_framework.tunable_model.tunable_model import SequenceTunableModelRegression, SequenceTunableModelClassification

#Data handlers
from ann_framework.data_handlers.data_handler_CMAPSS import CMAPSSDataHandler
from ann_framework.data_handlers.data_handler_MNIST import MNISTDataHandler
from ann_framework.data_handlers.data_handler_CIFAR10 import CIFAR10DataHandler

Using TensorFlow backend.


### Given a model, get the compiled model

In [2]:
def get_compiled_model(model, problem_type, optimizer_params=[]):
    """Obtain a keras compiled model"""
    
    #Shared parameters for the models
    optimizer = Adam(lr=0.001, beta_1=0.5)
    
    if problem_type == 1:
        lossFunction = "mean_squared_error"
        metrics = ["mse"]
    elif problem_type == 2:
        lossFunction = "categorical_crossentropy"
        metrics = ["accuracy"]
    else:
        print("Problem type not defined")
        model = None
        return
    
    #Create and compile the models
    model.compile(optimizer = optimizer, loss = lossFunction, metrics = metrics)
    
    return model


def create_tunable_model(model_genotype, problem_type, input_shape, data_handler, model_number):
    
    K.clear_session()
    
    model = fetch_to_keras.decode_genotype(model_genotype, problem_type, input_shape, 1)
    
    model = get_compiled_model(model, problem_type, optimizer_params=[])
    
    if problem_type == 1:
        tModel = SequenceTunableModelRegression('ModelReg_SN_'+str(model_number), model, lib_type='keras', data_handler=data_handler)
    else:
        tModel = SequenceTunableModelClassification('ModelClass_SN_'+str(model_number), model, lib_type='keras', data_handler=data_handler)
        
    return tModel

### Load cmaps data handler

In [3]:
def cmaps_dhandler(data_scaler=None):

    #Selected as per CNN paper
    features = ['T2', 'T24', 'T30', 'T50', 'P2', 'P15', 'P30', 'Nf', 'Nc', 'epr', 'Ps30', 'phi', 'NRf', 'NRc', 'BPR', 
    'farB', 'htBleed', 'Nf_dmd', 'PCNfR_dmd', 'W31', 'W32']
    selected_indices = np.array([2, 3, 4, 7, 8, 9, 11, 12, 13, 14, 15, 17, 20, 21])
    selected_features = list(features[i] for i in selected_indices-1)
    data_folder = '../CMAPSSData'

    window_size = 24
    window_stride = 1
    max_rul = 129

    dHandler_cmaps = CMAPSSDataHandler(data_folder, 1, selected_features,
                                       max_rul, window_size, window_stride, data_scaler=data_scaler)

    input_shape = (len(selected_features)*window_size, )

    return dHandler_cmaps

### Load models and evaluate model

In [4]:
def load_model(model_file, weights_file="", problem_type=1):
    
    p_type = ""
    
    # load json and create model
    json_file = open(model_file, 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)
    print("Loaded model from disk") 
        
    #Load weights if specified
    if weights_file != "":
        # load weights into new model
        loaded_model.load_weights(weights_file)
        print("Loaded weights from disk") 
    else:
        print("Model needs training")
        
    optimizer = Adam(lr=0.001, beta_1=0.5)
    
    if problem_type == 1:
        p_type = "regression"
        lossFunction = "mean_squared_error"
        metrics = ["mse"]
    elif problem_type == 2:
        p_type = "classification"
        lossFunction = "categorical_crossentropy"
        metrics = ["accuracy"]
    else:
        print("Problem type not defined")
        model = None
        return
    
    #Create and compile the models
    loaded_model.compile(optimizer = optimizer, loss = lossFunction, metrics = metrics)
    print("Created model for " + p_type + " with loss function " + lossFunction)

    return loaded_model
        
        

### Load each of the models and test them

In [5]:
best_model_folder = 'best_models'
"""
test_sets = {'cifar10':(CIFAR10DataHandler, None, 2), 
             'cmapss':(cmaps_dhandler, MinMaxScaler(feature_range=(-1, 1)), 1), 
             'mnist':((MNISTDataHandler), None, 2)}
"""

test_sets = {'mnist':((MNISTDataHandler), None, 2)}
#alpha_folders = ['alpha0.6', 'alpha0.8', 'alpha1']
#alpha_folders = ['alpha0.5']
alpha_values = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

In [6]:
results = {}

k = 5  #For 10-fold cross validation

for dataset in test_sets.keys():
    for alphaValue in alpha_values:
        
        model_file_name = 'scalarized/alpha{}/bestModel_global.json'.format(alphaValue)
        weights_file_name = 'scalarized/alpha{}/bestModel_global.h5'.format(alphaValue)
        trainable_count = 0
        
        print("Testing for "+model_file_name)
        
        results_key = dataset + "_" +  str(alphaValue)
        
        evaluations_cv = np.zeros(k)
        evaluations_test = np.zeros(k)
        
        model_location = best_model_folder + '/' + dataset + '/' + model_file_name
        
        if weights_file_name != "":
            weights_location = best_model_folder + '/' + dataset + '/' + weights_file_name
        
        dhandler, data_scaler, problem_type = test_sets[dataset]

        #model = load_model(model_location, weights_location, problem_type)   
        
        data_handler = dhandler(data_scaler=data_scaler)
        data_handler.load_data(verbose = 1)
        data_handler.print_data()
        
        folds = list(KFold(n_splits=k, shuffle=True).split(data_handler.X_train))
        
        print('Validation on model:' + model_location)
        
        for j, (train_idx, val_idx) in enumerate(folds):

            print('\nExperiment on Fold ', j)
            
            K.clear_session()  #Clear the previous tensorflow graph 

            X_train_cv = data_handler.X_train[train_idx]
            y_train_cv = data_handler.y_train[train_idx]
            X_valid_cv = data_handler.X_train[val_idx]
            y_valid_cv = data_handler.y_train[val_idx]

            model = load_model(model_location, "", problem_type)
            model.summary()
            trainable_count = int(np.sum([K.count_params(p) for p in set(model.trainable_weights)]))

            model.fit(X_train_cv, y_train_cv, batch_size=512, epochs=100, verbose=1)

            evaluation_cv = model.evaluate(X_valid_cv, y_valid_cv)
            evaluation_test = model.evaluate(data_handler.X_test, data_handler.y_test)

            evaluations_cv[j] = evaluation_cv[1]
            evaluations_test[j] = evaluation_test[1]
            
        results[results_key] = (evaluations_cv, evaluations_test, trainable_count)
        

Testing for scalarized/alpha0.2/bestModel_global.json
Loading data. Cross-Validation ratio 0
Printing shapes

Training data (X, y)
(60000, 784)
(60000, 10)
Testing data (X, y)
(10000, 784)
(10000, 10)
Printing first 5 elements

Training data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Testing data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Validation on model:best_models/mnist/scalarized/alpha0.2/bestModel_global.json

Experiment on Fold  0
Loaded model from disk
Model needs training


48000/48000 [==============================] - 0s 6us/step - loss: 1.9509e-04 - acc: 1.0000
Epoch 64/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.8633e-04 - acc: 1.0000
Epoch 65/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.7530e-04 - acc: 1.0000
Epoch 66/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.6230e-04 - acc: 1.0000
Epoch 67/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.5424e-04 - acc: 1.0000
Epoch 68/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.4562e-04 - acc: 1.0000
Epoch 69/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.3652e-04 - acc: 1.0000
Epoch 70/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.2898e-04 - acc: 1.0000
Epoch 71/100
48000/48000 [==============================] - 0s 6us/step - loss: 1.2153e-04 - acc: 1.0000
Epoch 72/100
48000/48000 [==============================] - 0s 6us/s

Epoch 33/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0022 - acc: 0.9999
Epoch 34/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0016 - acc: 1.0000
Epoch 35/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0013 - acc: 1.0000
Epoch 36/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0011 - acc: 1.0000
Epoch 37/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0011 - acc: 1.0000
Epoch 38/100
48000/48000 [==============================] - 0s 6us/step - loss: 9.9951e-04 - acc: 1.0000
Epoch 39/100
48000/48000 [==============================] - 0s 6us/step - loss: 9.3816e-04 - acc: 1.0000
Epoch 40/100
48000/48000 [==============================] - 0s 6us/step - loss: 8.7114e-04 - acc: 1.0000
Epoch 41/100
48000/48000 [==============================] - 0s 6us/step - loss: 8.2649e-04 - acc: 1.0000
Epoch 42/100
48000/48000 [==============================] - 0s 6us/step - l

48000/48000 [==============================] - 0s 8us/step - loss: 0.5790 - acc: 0.8451
Epoch 2/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.2223 - acc: 0.9358
Epoch 3/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.1689 - acc: 0.9506
Epoch 4/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.1367 - acc: 0.9607
Epoch 5/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.1143 - acc: 0.9670
Epoch 6/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0982 - acc: 0.9709
Epoch 7/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0837 - acc: 0.9756
Epoch 8/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0729 - acc: 0.9783
Epoch 9/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0646 - acc: 0.9807
Epoch 10/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0554 - acc: 0.9832
Epoch 11/10

48000/48000 [==============================] - 0s 6us/step - loss: 6.1563e-05 - acc: 1.0000
Epoch 81/100
48000/48000 [==============================] - 0s 6us/step - loss: 5.7956e-05 - acc: 1.0000
Epoch 82/100
48000/48000 [==============================] - 0s 6us/step - loss: 5.5462e-05 - acc: 1.0000
Epoch 83/100
48000/48000 [==============================] - 0s 6us/step - loss: 5.1971e-05 - acc: 1.0000
Epoch 84/100
48000/48000 [==============================] - 0s 6us/step - loss: 4.8994e-05 - acc: 1.0000
Epoch 85/100
48000/48000 [==============================] - 0s 6us/step - loss: 4.6195e-05 - acc: 1.0000
Epoch 86/100
48000/48000 [==============================] - 0s 6us/step - loss: 4.4560e-05 - acc: 1.0000
Epoch 87/100
48000/48000 [==============================] - 0s 6us/step - loss: 4.1500e-05 - acc: 1.0000
Epoch 88/100
48000/48000 [==============================] - 0s 6us/step - loss: 3.9481e-05 - acc: 1.0000
Epoch 89/100
48000/48000 [==============================] - 0s 6us/s

48000/48000 [==============================] - 0s 6us/step - loss: 9.7592e-04 - acc: 1.0000
Epoch 51/100
48000/48000 [==============================] - 0s 6us/step - loss: 9.3108e-04 - acc: 1.0000
Epoch 52/100
48000/48000 [==============================] - 0s 6us/step - loss: 8.8362e-04 - acc: 1.0000
Epoch 53/100
48000/48000 [==============================] - 0s 6us/step - loss: 8.2907e-04 - acc: 1.0000
Epoch 54/100
48000/48000 [==============================] - 0s 6us/step - loss: 7.9240e-04 - acc: 1.0000
Epoch 55/100
48000/48000 [==============================] - 0s 6us/step - loss: 7.5887e-04 - acc: 1.0000
Epoch 56/100
48000/48000 [==============================] - 0s 6us/step - loss: 7.2466e-04 - acc: 1.0000
Epoch 57/100
48000/48000 [==============================] - 0s 6us/step - loss: 6.9423e-04 - acc: 1.0000
Epoch 58/100
48000/48000 [==============================] - 0s 6us/step - loss: 6.6861e-04 - acc: 1.0000
Epoch 59/100
48000/48000 [==============================] - 0s 6us/s

48000/48000 [==============================] - 0s 6us/step - loss: 0.0149 - acc: 0.9965A: 0s - loss: 0.0136 - acc: 0.9
Epoch 20/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0127 - acc: 0.9972
Epoch 21/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0122 - acc: 0.9970
Epoch 22/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0111 - acc: 0.9976
Epoch 23/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0103 - acc: 0.9978
Epoch 24/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0076 - acc: 0.9986
Epoch 25/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0055 - acc: 0.9994
Epoch 26/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0046 - acc: 0.9996
Epoch 27/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.0044 - acc: 0.9993
Epoch 28/100
48000/48000 [==============================] - 0s 6us/step -

48000/48000 [==============================] - 0s 6us/step - loss: 4.3246e-04 - acc: 1.0000
Epoch 99/100
48000/48000 [==============================] - 0s 6us/step - loss: 4.2718e-04 - acc: 1.0000
Epoch 100/100
10000/10000 [==============================] - 0s 12us/step
Testing for scalarized/alpha0.3/bestModel_global.json
Loading data. Cross-Validation ratio 0
Printing shapes

Training data (X, y)
(60000, 784)
(60000, 10)
Testing data (X, y)
(10000, 784)
(10000, 10)
Printing first 5 elements

Training data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Testing data (X, y)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1

48000/48000 [==============================] - 0s 8us/step - loss: 0.0112 - acc: 0.9958
Epoch 59/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0117 - acc: 0.9961
Epoch 60/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0105 - acc: 0.9966
Epoch 61/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0118 - acc: 0.9956
Epoch 62/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0108 - acc: 0.9962
Epoch 63/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0099 - acc: 0.9964
Epoch 64/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0098 - acc: 0.9966
Epoch 65/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0113 - acc: 0.9960
Epoch 66/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0101 - acc: 0.9965
Epoch 67/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0094 - acc: 0.9967
Epo

48000/48000 [==============================] - 0s 8us/step - loss: 0.0215 - acc: 0.9929
Epoch 29/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0196 - acc: 0.9935
Epoch 30/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0200 - acc: 0.9930
Epoch 31/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0193 - acc: 0.9933
Epoch 32/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0175 - acc: 0.9942
Epoch 33/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0164 - acc: 0.9943
Epoch 34/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0162 - acc: 0.9944
Epoch 35/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0180 - acc: 0.9936
Epoch 36/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0150 - acc: 0.9950
Epoch 37/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0166 - acc: 0.9946
Epo

Epoch 1/100
48000/48000 [==============================] - 0s 10us/step - loss: 0.5820 - acc: 0.8372
Epoch 2/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.2373 - acc: 0.9313
Epoch 3/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.1765 - acc: 0.9489
Epoch 4/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.1427 - acc: 0.9583
Epoch 5/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.1217 - acc: 0.9633
Epoch 6/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.1037 - acc: 0.9688
Epoch 7/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0916 - acc: 0.9717
Epoch 8/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0802 - acc: 0.9754
Epoch 9/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0714 - acc: 0.9776
Epoch 10/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0640 - acc: 0.979

48000/48000 [==============================] - 0s 8us/step - loss: 0.0075 - acc: 0.9974
Epoch 83/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0084 - acc: 0.9973
Epoch 84/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0095 - acc: 0.9965
Epoch 85/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0082 - acc: 0.9971
Epoch 86/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0085 - acc: 0.9972
Epoch 87/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0085 - acc: 0.9967
Epoch 88/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0083 - acc: 0.9969
Epoch 89/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0084 - acc: 0.9970
Epoch 90/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0084 - acc: 0.9972
Epoch 91/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0081 - acc: 0.9970
Epo

48000/48000 [==============================] - 0s 8us/step - loss: 0.0119 - acc: 0.9957
Epoch 53/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0118 - acc: 0.9959
Epoch 54/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0096 - acc: 0.9967
Epoch 55/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0107 - acc: 0.9963
Epoch 56/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0108 - acc: 0.9962
Epoch 57/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0119 - acc: 0.9960
Epoch 58/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0106 - acc: 0.9961
Epoch 59/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0098 - acc: 0.9969
Epoch 60/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0101 - acc: 0.9966
Epoch 61/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0094 - acc: 0.9969
Epo

48000/48000 [==============================] - 0s 8us/step - loss: 0.0284 - acc: 0.9905
Epoch 23/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0262 - acc: 0.9911
Epoch 24/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0242 - acc: 0.9920
Epoch 25/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0218 - acc: 0.9931
Epoch 26/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0243 - acc: 0.9921
Epoch 27/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0207 - acc: 0.9930
Epoch 28/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0205 - acc: 0.9934
Epoch 29/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0201 - acc: 0.9931
Epoch 30/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0185 - acc: 0.9937
Epoch 31/100
48000/48000 [==============================] - 0s 8us/step - loss: 0.0202 - acc: 0.9927
Epo

Epoch 1/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.8197 - acc: 0.7739
Epoch 2/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.3010 - acc: 0.9137
Epoch 3/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.2498 - acc: 0.9274
Epoch 4/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.2153 - acc: 0.9379
Epoch 5/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1916 - acc: 0.9444
Epoch 6/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1732 - acc: 0.9498
Epoch 7/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1579 - acc: 0.9545
Epoch 8/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1461 - acc: 0.9571
Epoch 9/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1358 - acc: 0.9603
Epoch 10/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1284 - acc: 0.9625

48000/48000 [==============================] - 0s 4us/step - loss: 0.0053 - acc: 0.9993
Epoch 83/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0047 - acc: 0.9994
Epoch 84/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0085 - acc: 0.9980
Epoch 85/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0051 - acc: 0.9993
Epoch 86/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0041 - acc: 0.9997
Epoch 87/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0034 - acc: 0.9997
Epoch 88/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0037 - acc: 0.9995
Epoch 89/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0063 - acc: 0.9986
Epoch 90/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0148 - acc: 0.9956
Epoch 91/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0097 - acc: 0.9972
Epo

48000/48000 [==============================] - 0s 4us/step - loss: 0.0165 - acc: 0.9962
Epoch 54/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0169 - acc: 0.9957
Epoch 55/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0155 - acc: 0.9964
Epoch 56/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0139 - acc: 0.9971
Epoch 57/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0144 - acc: 0.9968
Epoch 58/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0135 - acc: 0.9970
Epoch 59/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0120 - acc: 0.9975
Epoch 60/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0123 - acc: 0.9974
Epoch 61/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0108 - acc: 0.9979
Epoch 62/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0103 - acc: 0.9980
Epo

48000/48000 [==============================] - 0s 4us/step - loss: 0.0673 - acc: 0.9802
Epoch 25/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0639 - acc: 0.9809
Epoch 26/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0617 - acc: 0.9819
Epoch 27/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0594 - acc: 0.9822
Epoch 28/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0569 - acc: 0.9832
Epoch 29/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0548 - acc: 0.9838
Epoch 30/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0534 - acc: 0.9840
Epoch 31/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0497 - acc: 0.9862
Epoch 32/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0486 - acc: 0.9858
Epoch 33/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0477 - acc: 0.9860
Epo

Epoch 1/100
48000/48000 [==============================] - 0s 6us/step - loss: 0.8403 - acc: 0.7723
Epoch 2/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.3039 - acc: 0.9125
Epoch 3/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.2519 - acc: 0.9276
Epoch 4/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.2180 - acc: 0.9367
Epoch 5/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1917 - acc: 0.9439
Epoch 6/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1729 - acc: 0.9495
Epoch 7/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1569 - acc: 0.9535
Epoch 8/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1445 - acc: 0.9580
Epoch 9/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1341 - acc: 0.9608
Epoch 10/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.1245 - acc: 0.9638

48000/48000 [==============================] - 0s 4us/step - loss: 0.0036 - acc: 0.9998
Epoch 83/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0152 - acc: 0.9959
Epoch 84/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0067 - acc: 0.9984
Epoch 85/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0036 - acc: 0.9998
Epoch 86/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0031 - acc: 0.9998
Epoch 87/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0038 - acc: 0.9996
Epoch 88/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0028 - acc: 0.9999
Epoch 89/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0024 - acc: 1.0000
Epoch 90/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0022 - acc: 1.0000
Epoch 91/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0022 - acc: 0.9999
Epo

48000/48000 [==============================] - 0s 4us/step - loss: 0.0210 - acc: 0.9944
Epoch 54/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0194 - acc: 0.9951
Epoch 55/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0183 - acc: 0.9957
Epoch 56/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0184 - acc: 0.9955
Epoch 57/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0174 - acc: 0.9955
Epoch 58/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0162 - acc: 0.9962
Epoch 59/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0158 - acc: 0.9965
Epoch 60/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0150 - acc: 0.9968
Epoch 61/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0138 - acc: 0.9970
Epoch 62/100
48000/48000 [==============================] - 0s 4us/step - loss: 0.0136 - acc: 0.9970
Epo

Epoch 14/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3607 - acc: 0.8983
Epoch 15/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3527 - acc: 0.8998
Epoch 16/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3444 - acc: 0.9021
Epoch 17/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3422 - acc: 0.9036
Epoch 18/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3374 - acc: 0.9035
Epoch 19/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3338 - acc: 0.9057
Epoch 20/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3317 - acc: 0.9059
Epoch 21/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3236 - acc: 0.9073
Epoch 22/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3219 - acc: 0.9081
Epoch 23/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3222 - ac

48000/48000 [==============================] - 0s 3us/step - loss: 0.2445 - acc: 0.9280
Epoch 96/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2448 - acc: 0.9278
Epoch 97/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2447 - acc: 0.9283
Epoch 98/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2450 - acc: 0.9279
Epoch 99/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2444 - acc: 0.9282
Epoch 100/100
10000/10000 [==============================] - 0s 6us/step

Experiment on Fold  1
Loaded model from disk
Model needs training
Created model for classification with loss function categorical_crossentropy
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
in (Dense)                   (None, 8)                 6280      
_________________________________________________________________
dense_1 (Dense)            

48000/48000 [==============================] - 0s 3us/step - loss: 0.2550 - acc: 0.9261
Epoch 66/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2529 - acc: 0.9263
Epoch 67/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2536 - acc: 0.9248
Epoch 68/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2507 - acc: 0.9266
Epoch 69/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2493 - acc: 0.9265
Epoch 70/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2510 - acc: 0.9278
Epoch 71/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2473 - acc: 0.9274
Epoch 72/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2481 - acc: 0.9280
Epoch 73/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2493 - acc: 0.9280
Epoch 74/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2477 - acc: 0.9277
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2822 - acc: 0.9202
Epoch 36/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2792 - acc: 0.9211
Epoch 37/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2781 - acc: 0.9216
Epoch 38/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2752 - acc: 0.9225
Epoch 39/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2744 - acc: 0.9223
Epoch 40/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2743 - acc: 0.9229
Epoch 41/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2726 - acc: 0.9219
Epoch 42/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2691 - acc: 0.9248
Epoch 43/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2680 - acc: 0.9256
Epoch 44/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2660 - acc: 0.9251
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.4518 - acc: 0.8692
Epoch 6/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4310 - acc: 0.8769
Epoch 7/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4179 - acc: 0.8821
Epoch 8/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3991 - acc: 0.8864
Epoch 9/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3891 - acc: 0.8896
Epoch 10/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3786 - acc: 0.8933
Epoch 11/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3738 - acc: 0.8937
Epoch 12/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3644 - acc: 0.8956
Epoch 13/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3561 - acc: 0.8983
Epoch 14/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3494 - acc: 0.9010
Epoch 1

48000/48000 [==============================] - 0s 3us/step - loss: 0.2403 - acc: 0.9285
Epoch 87/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2382 - acc: 0.9291
Epoch 88/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2385 - acc: 0.9302
Epoch 89/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2389 - acc: 0.9316
Epoch 90/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2396 - acc: 0.9306
Epoch 91/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2383 - acc: 0.9298
Epoch 92/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2345 - acc: 0.9302
Epoch 93/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2364 - acc: 0.9285
Epoch 94/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2379 - acc: 0.9301
Epoch 95/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2388 - acc: 0.9293
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2815 - acc: 0.9188
Epoch 57/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2775 - acc: 0.9200
Epoch 58/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2782 - acc: 0.9211
Epoch 59/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2764 - acc: 0.9209
Epoch 60/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2788 - acc: 0.9183
Epoch 61/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2775 - acc: 0.9201
Epoch 62/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2734 - acc: 0.9208
Epoch 63/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2744 - acc: 0.9198
Epoch 64/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2714 - acc: 0.9204
Epoch 65/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2705 - acc: 0.9220
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.1108 - acc: 0.9695
Epoch 20/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1067 - acc: 0.9709
Epoch 21/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1026 - acc: 0.9723
Epoch 22/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0988 - acc: 0.9730
Epoch 23/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0958 - acc: 0.9738
Epoch 24/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0921 - acc: 0.9751
Epoch 25/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0887 - acc: 0.9760
Epoch 26/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0856 - acc: 0.9771
Epoch 27/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0826 - acc: 0.9778
Epoch 28/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0798 - acc: 0.9787
Epo

10000/10000 [==============================] - 0s 6us/step

Experiment on Fold  1
Loaded model from disk
Model needs training
Created model for classification with loss function categorical_crossentropy
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
in (Dense)                   (None, 40)                31400     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                410       
Total params: 31,810
Trainable params: 31,810
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
48000/48000 [==============================] - 0s 5us/step - loss: 0.9148 - acc: 0.7880
Epoch 2/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4131 - acc: 0.8964
Epoch 3/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3231 - acc: 0.9146
Epoch 4/100
48000/48000 [======

48000/48000 [==============================] - 0s 3us/step - loss: 0.0182 - acc: 0.9978
Epoch 73/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0175 - acc: 0.9981
Epoch 74/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0169 - acc: 0.9982
Epoch 75/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0165 - acc: 0.9983
Epoch 76/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0159 - acc: 0.9982
Epoch 77/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0154 - acc: 0.9984
Epoch 78/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0148 - acc: 0.9984
Epoch 79/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0144 - acc: 0.9986
Epoch 80/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0138 - acc: 0.9986
Epoch 81/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0134 - acc: 0.9989
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.0444 - acc: 0.9901
Epoch 45/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0430 - acc: 0.9900
Epoch 46/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0417 - acc: 0.9907
Epoch 47/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0404 - acc: 0.9910
Epoch 48/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0390 - acc: 0.9914
Epoch 49/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0376 - acc: 0.9919
Epoch 50/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0366 - acc: 0.9920
Epoch 51/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0353 - acc: 0.9926
Epoch 52/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0342 - acc: 0.9929
Epoch 53/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0329 - acc: 0.9937
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.1287 - acc: 0.9639
Epoch 17/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1231 - acc: 0.9662
Epoch 18/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1178 - acc: 0.9677
Epoch 19/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1127 - acc: 0.9691
Epoch 20/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1085 - acc: 0.9701
Epoch 21/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.1042 - acc: 0.9715
Epoch 22/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0998 - acc: 0.9728
Epoch 23/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0965 - acc: 0.9734
Epoch 24/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0924 - acc: 0.9752
Epoch 25/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0893 - acc: 0.9756
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.0078 - acc: 0.9997
Epoch 98/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0075 - acc: 0.9997
Epoch 99/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0073 - acc: 0.9997
Epoch 100/100
10000/10000 [==============================] - 0s 6us/step

Experiment on Fold  4
Loaded model from disk
Model needs training
Created model for classification with loss function categorical_crossentropy
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
in (Dense)                   (None, 40)                31400     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                410       
Total params: 31,810
Trainable params: 31,810
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
48000/48000 [==

48000/48000 [==============================] - 0s 3us/step - loss: 0.0199 - acc: 0.9974
Epoch 70/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0192 - acc: 0.9976
Epoch 71/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0185 - acc: 0.9978
Epoch 72/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0180 - acc: 0.9977
Epoch 73/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0174 - acc: 0.9978
Epoch 74/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0169 - acc: 0.9982
Epoch 75/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0163 - acc: 0.9981
Epoch 76/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0157 - acc: 0.9984
Epoch 77/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0153 - acc: 0.9983
Epoch 78/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.0147 - acc: 0.9985
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2519 - acc: 0.9304
Epoch 33/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2509 - acc: 0.9303
Epoch 34/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2494 - acc: 0.9307
Epoch 35/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2483 - acc: 0.9312
Epoch 36/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2472 - acc: 0.9307
Epoch 37/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2458 - acc: 0.9319
Epoch 38/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2452 - acc: 0.9309
Epoch 39/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2443 - acc: 0.9323
Epoch 40/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2430 - acc: 0.9328
Epoch 41/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2425 - acc: 0.9324
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.4989 - acc: 0.8669
Epoch 5/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4262 - acc: 0.8823
Epoch 6/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3883 - acc: 0.8922
Epoch 7/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3634 - acc: 0.8986
Epoch 8/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3454 - acc: 0.9031
Epoch 9/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3310 - acc: 0.9076
Epoch 10/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3198 - acc: 0.9099
Epoch 11/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3100 - acc: 0.9134
Epoch 12/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3019 - acc: 0.9150
Epoch 13/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2952 - acc: 0.9165
Epoch 14

48000/48000 [==============================] - 0s 3us/step - loss: 0.2092 - acc: 0.9409
Epoch 86/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2091 - acc: 0.9406
Epoch 87/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2086 - acc: 0.9412
Epoch 88/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2080 - acc: 0.9412
Epoch 89/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2077 - acc: 0.9411
Epoch 90/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2076 - acc: 0.9420
Epoch 91/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2073 - acc: 0.9418
Epoch 92/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2070 - acc: 0.9415
Epoch 93/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2065 - acc: 0.9414
Epoch 94/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2060 - acc: 0.9416
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2260 - acc: 0.9372
Epoch 58/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2260 - acc: 0.9377
Epoch 59/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2251 - acc: 0.9383
Epoch 60/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2244 - acc: 0.9369
Epoch 61/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2241 - acc: 0.9376
Epoch 62/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2236 - acc: 0.9379
Epoch 63/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2231 - acc: 0.9380
Epoch 64/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2222 - acc: 0.9380
Epoch 65/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2218 - acc: 0.9384
Epoch 66/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2213 - acc: 0.9388
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2585 - acc: 0.9275
Epoch 30/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2570 - acc: 0.9281
Epoch 31/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2556 - acc: 0.9282
Epoch 32/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2544 - acc: 0.9282
Epoch 33/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2533 - acc: 0.9287
Epoch 34/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2519 - acc: 0.9291
Epoch 35/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2510 - acc: 0.9293
Epoch 36/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2496 - acc: 0.9297
Epoch 37/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2488 - acc: 0.9296
Epoch 38/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2476 - acc: 0.9306
Epo

48000/48000 [==============================] - 0s 4us/step - loss: 1.5657 - acc: 0.5498
Epoch 2/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.8114 - acc: 0.8119
Epoch 3/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.5865 - acc: 0.8500
Epoch 4/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4982 - acc: 0.8651
Epoch 5/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4492 - acc: 0.8767
Epoch 6/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.4168 - acc: 0.8829
Epoch 7/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3934 - acc: 0.8883
Epoch 8/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3754 - acc: 0.8933
Epoch 9/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3614 - acc: 0.8972
Epoch 10/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.3496 - acc: 0.9003
Epoch 11/10

48000/48000 [==============================] - 0s 3us/step - loss: 0.2164 - acc: 0.9396
Epoch 83/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2159 - acc: 0.9394
Epoch 84/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2154 - acc: 0.9401
Epoch 85/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2150 - acc: 0.9397
Epoch 86/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2145 - acc: 0.9402
Epoch 87/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2140 - acc: 0.9401
Epoch 88/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2134 - acc: 0.9401
Epoch 89/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2130 - acc: 0.9408
Epoch 90/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2127 - acc: 0.9401
Epoch 91/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2120 - acc: 0.9410
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2300 - acc: 0.9354
Epoch 46/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2297 - acc: 0.9355
Epoch 47/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2285 - acc: 0.9361
Epoch 48/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2281 - acc: 0.9358
Epoch 49/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2272 - acc: 0.9354
Epoch 50/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2265 - acc: 0.9364
Epoch 51/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2260 - acc: 0.9360
Epoch 52/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2253 - acc: 0.9362
Epoch 53/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2248 - acc: 0.9364
Epoch 54/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2243 - acc: 0.9371
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2881 - acc: 0.9201
Epoch 18/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2854 - acc: 0.9208
Epoch 19/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2826 - acc: 0.9220
Epoch 20/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2797 - acc: 0.9230
Epoch 21/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2772 - acc: 0.9234
Epoch 22/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2748 - acc: 0.9237
Epoch 23/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2728 - acc: 0.9238
Epoch 24/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2708 - acc: 0.9251
Epoch 25/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2691 - acc: 0.9259
Epoch 26/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2672 - acc: 0.9261
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2108 - acc: 0.9402
Epoch 99/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2102 - acc: 0.9406
Epoch 100/100
10000/10000 [==============================] - 0s 5us/step

Experiment on Fold  2
Loaded model from disk
Model needs training
Created model for classification with loss function categorical_crossentropy
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
in (Dense)                   (None, 8)                 6280      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                90        
Total params: 6,370
Trainable params: 6,370
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
48000/48000 [==============================] - 0s 5us/step - loss: 1.5501 - acc: 0.5383
Epoch 2/100
48000/48000 [=====

48000/48000 [==============================] - 0s 3us/step - loss: 0.2370 - acc: 0.9329
Epoch 71/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2364 - acc: 0.9327
Epoch 72/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2356 - acc: 0.9330
Epoch 73/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2357 - acc: 0.9336
Epoch 74/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2349 - acc: 0.9330
Epoch 75/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2346 - acc: 0.9334
Epoch 76/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2339 - acc: 0.9336
Epoch 77/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2333 - acc: 0.9334
Epoch 78/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2328 - acc: 0.9339
Epoch 79/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2327 - acc: 0.9338
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2426 - acc: 0.9310
Epoch 43/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2418 - acc: 0.9316
Epoch 44/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2403 - acc: 0.9318
Epoch 45/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2399 - acc: 0.9320
Epoch 46/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2390 - acc: 0.9321
Epoch 47/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2382 - acc: 0.9323
Epoch 48/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2372 - acc: 0.9323
Epoch 49/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2362 - acc: 0.9329
Epoch 50/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2352 - acc: 0.9333
Epoch 51/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2349 - acc: 0.9323
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2936 - acc: 0.9171
Epoch 15/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2892 - acc: 0.9181
Epoch 16/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2856 - acc: 0.9202
Epoch 17/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2823 - acc: 0.9210
Epoch 18/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2794 - acc: 0.9223
Epoch 19/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2768 - acc: 0.9227
Epoch 20/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2738 - acc: 0.9235
Epoch 21/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2715 - acc: 0.9242
Epoch 22/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2697 - acc: 0.9241
Epoch 23/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2672 - acc: 0.9257
Epo

48000/48000 [==============================] - 0s 3us/step - loss: 0.2069 - acc: 0.9415
Epoch 96/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2068 - acc: 0.9410
Epoch 97/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2065 - acc: 0.9420
Epoch 98/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2059 - acc: 0.9421
Epoch 99/100
48000/48000 [==============================] - 0s 3us/step - loss: 0.2054 - acc: 0.9420
Epoch 100/100
10000/10000 [==============================] - 0s 5us/step


### Print the stats

In [7]:
for key in results.keys():
    
    print("\nStats for: ")
    print(key)
    evaluations_cv, evaluations_test, model_size = results[key]
    
    print("\nModel size: %d"%model_size)
    
    print("\nCrossVal stats: ")
    print(evaluations_cv)
    print(stats.describe(evaluations_cv))
    
    print("\nTest stats: ")
    print(stats.describe(evaluations_test))


Stats for: 
mnist_0.2

Model size: 106330

CrossVal stats: 
[0.97683333 0.97591667 0.9765     0.97558333 0.97725   ]
DescribeResult(nobs=5, minmax=(0.9755833333333334, 0.97725), mean=0.9764166666666666, variance=4.548611111110849e-07, skewness=-0.04745430034285107, kurtosis=-1.403210768603311)

Test stats: 
DescribeResult(nobs=5, minmax=(0.9767, 0.9785), mean=0.9778400000000002, variance=5.580000000000081e-07, skewness=-0.6974994435346632, kurtosis=-0.9977357690671402)

Stats for: 
mnist_0.3

Model size: 161962

CrossVal stats: 
[0.979      0.98058333 0.98025    0.98358333 0.98008333]
DescribeResult(nobs=5, minmax=(0.979, 0.9835833333333334), mean=0.9806999999999999, variance=2.9500000000000785e-06, skewness=1.0332748778123741, kurtosis=-0.21150415083978036)

Test stats: 
DescribeResult(nobs=5, minmax=(0.9812, 0.9822), mean=0.9819000000000001, variance=1.799999999999992e-07, skewness=-1.0321322918616536, kurtosis=-0.5115740740724712)

Stats for: 
mnist_0.4

Model size: 25570

CrossVal